### ISSUE TITLE
FEATURE: Dungeons Functionalities

### ISSUE THREAD

**Issue by OcelotWalrus** [Dungeons-of-Kathallion/Bane-Of-Wargs#89]
### Is your feature request related to a problem? Please describe.

There isn't any way of creating a proper dungeon in the game.

### Describe the solution you'd like

A dungeon will be a new map zone type, which'll be interactive, as hostels and etc...
When you'll run the `Z` command, it'll display a generic menu that have these options:

1. Enter Dungeon
2. See Dungeon Map
3. Exit

- When selecting the option 1, it'll make you enter the dungeon and a new UI will be launched. See below. 
- When selecting the option 2, it'll display a small ASCII art map of the dungeon. This options will not always be there, it'll depends on the dungeon data. (some dungeon won't have any map).

---

About the new UI: the 'dungeon UI':

```yaml
=======================================================
Defy the dungeon <dungeon name>!
=======================================================
PROGRESS: 24% |███_______|
=======================================================
CURRENT ROOM: <room number>
TYPE: <room type>
=======================================================
  - [S]tart Room
  - [C]heck Dungeon Map
  - [I]nventory
  - [P]ause game
  - [E]xit Dungeon
=======================================================

> 

```

The player will start by the room 1, the room starts when he decide. If he succeed, he access to the next room, and the room will start when he decide. Once he complete the dungeon, a dialog will be shown. Exiting the dungeon will abort the process and the player will have to start over. Once the player starts a dungeon, he'll have to finish it, before being able to quit or save the game.

---

And the definition of a dungeon:

```html
Cool Dungeon:
  [normal map zone data]
  dungeon:
    name: <dungeon display name(str)>
    dungeon map: <img name(str)>  # not required
    rooms number: <number of rooms(int)>
    reward dialog: <dialog id(str)>
    rooms:
      <room id>:
        room type: <fight | enigma | boss-fight>  # any ideas?
        room digit: <number of the room(int)>
        room fight data:  # if this is a fight or boss-fight room
          enemy list spawn: <enemy list id(str)>
          item reward: <item id(str)>  # not required. Maybe other types of reward?
          gold reward: <payment(float)>  # not required. Maybe other types of reward?
        room enigma data:
          script name: <script name.py(str)>
          arguments: <variables id(list)>  # not required
```

### Additional Context

How the dungeons will be handled in the player data will be pretty much the same as missions are.
